import type { Metadata } from "next";
import { Providers } from "./providers/Provider";
import { fontSans, fontMono } from "./fonts/fonts";
import clsx from "clsx";
import "./globals.css";
import NavBar from "./NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={clsx(fontSans.variable, fontMono.variable)} >
      <body
      >
        <Providers>
          <NavBar />
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
