import type { Metadata } from "next";
import { Providers } from "./providers/Provider";
import { fontSans, fontMono } from "./fonts/fonts";
// import clsx from "clsx";
import "./globals.css";
import NavBar from "./NavBar";
import classNames from "classnames";
import { Container } from "@chakra-ui/react";
import AuthProvider from "./auth/Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={classNames(fontSans.variable, fontMono.variable)} >
      <body
      >
        <AuthProvider>
          <Providers>
            <NavBar />
            <main
              className="p-5"
              style={{ minHeight: "calc(100vh - 64px)" }}
            >
              <Container
                maxW="container.xl"
              >
                {children}
              </Container>
            </main>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
